<?php
/**
 * ClockifySettingsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Skriptfabrik\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * skriptfabrik API
 *
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Skriptfabrik\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Skriptfabrik\ApiClient\ApiException;
use Skriptfabrik\ApiClient\Configuration;
use Skriptfabrik\ApiClient\HeaderSelector;
use Skriptfabrik\ApiClient\ObjectSerializer;

/**
 * ClockifySettingsApi Class Doc Comment
 *
 * @category Class
 * @package  Skriptfabrik\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClockifySettingsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createClockifySettings' => [
            'application/vnd.api+json',
        ],
        'deleteClockifySettings' => [
            'application/json',
        ],
        'getClockifySettings' => [
            'application/json',
        ],
        'getClockifySettingsCollection' => [
            'application/json',
        ],
        'updateClockifySettings' => [
            'application/vnd.api+json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createClockifySettings
     *
     * Create Clockify Settings
     *
     * @param  string $include The Include Query Parameter. (optional)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsCreateRequest $clockify_settings_create_request Create Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createClockifySettings'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Skriptfabrik\ApiClient\Model\ClockifySettingsResponse|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError
     */
    public function createClockifySettings($include = null, $clockify_settings_create_request = null, string $contentType = self::contentTypes['createClockifySettings'][0])
    {
        list($response) = $this->createClockifySettingsWithHttpInfo($include, $clockify_settings_create_request, $contentType);
        return $response;
    }

    /**
     * Operation createClockifySettingsWithHttpInfo
     *
     * Create Clockify Settings
     *
     * @param  string $include The Include Query Parameter. (optional)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsCreateRequest $clockify_settings_create_request Create Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createClockifySettings'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Skriptfabrik\ApiClient\Model\ClockifySettingsResponse|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createClockifySettingsWithHttpInfo($include = null, $clockify_settings_create_request = null, string $contentType = self::contentTypes['createClockifySettings'][0])
    {
        $request = $this->createClockifySettingsRequest($include, $clockify_settings_create_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Skriptfabrik\ApiClient\Model\JsonApiError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\JsonApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\JsonApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Skriptfabrik\ApiClient\Model\JsonApiError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\JsonApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\JsonApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Skriptfabrik\ApiClient\Model\JsonApiError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\JsonApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\JsonApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createClockifySettingsAsync
     *
     * Create Clockify Settings
     *
     * @param  string $include The Include Query Parameter. (optional)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsCreateRequest $clockify_settings_create_request Create Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createClockifySettingsAsync($include = null, $clockify_settings_create_request = null, string $contentType = self::contentTypes['createClockifySettings'][0])
    {
        return $this->createClockifySettingsAsyncWithHttpInfo($include, $clockify_settings_create_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createClockifySettingsAsyncWithHttpInfo
     *
     * Create Clockify Settings
     *
     * @param  string $include The Include Query Parameter. (optional)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsCreateRequest $clockify_settings_create_request Create Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createClockifySettingsAsyncWithHttpInfo($include = null, $clockify_settings_create_request = null, string $contentType = self::contentTypes['createClockifySettings'][0])
    {
        $returnType = '\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse';
        $request = $this->createClockifySettingsRequest($include, $clockify_settings_create_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createClockifySettings'
     *
     * @param  string $include The Include Query Parameter. (optional)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsCreateRequest $clockify_settings_create_request Create Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createClockifySettingsRequest($include = null, $clockify_settings_create_request = null, string $contentType = self::contentTypes['createClockifySettings'][0])
    {




        $resourcePath = '/api/admin/clockify_settings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include,
            'include', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($clockify_settings_create_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($clockify_settings_create_request));
            } else {
                $httpBody = $clockify_settings_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteClockifySettings
     *
     * Delete Clockify Settings
     *
     * @param  string $clockify_settings_id clockify_settings_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteClockifySettings'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteClockifySettings($clockify_settings_id, string $contentType = self::contentTypes['deleteClockifySettings'][0])
    {
        $this->deleteClockifySettingsWithHttpInfo($clockify_settings_id, $contentType);
    }

    /**
     * Operation deleteClockifySettingsWithHttpInfo
     *
     * Delete Clockify Settings
     *
     * @param  string $clockify_settings_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteClockifySettings'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteClockifySettingsWithHttpInfo($clockify_settings_id, string $contentType = self::contentTypes['deleteClockifySettings'][0])
    {
        $request = $this->deleteClockifySettingsRequest($clockify_settings_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteClockifySettingsAsync
     *
     * Delete Clockify Settings
     *
     * @param  string $clockify_settings_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteClockifySettingsAsync($clockify_settings_id, string $contentType = self::contentTypes['deleteClockifySettings'][0])
    {
        return $this->deleteClockifySettingsAsyncWithHttpInfo($clockify_settings_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteClockifySettingsAsyncWithHttpInfo
     *
     * Delete Clockify Settings
     *
     * @param  string $clockify_settings_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteClockifySettingsAsyncWithHttpInfo($clockify_settings_id, string $contentType = self::contentTypes['deleteClockifySettings'][0])
    {
        $returnType = '';
        $request = $this->deleteClockifySettingsRequest($clockify_settings_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteClockifySettings'
     *
     * @param  string $clockify_settings_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteClockifySettingsRequest($clockify_settings_id, string $contentType = self::contentTypes['deleteClockifySettings'][0])
    {

        // verify the required parameter 'clockify_settings_id' is set
        if ($clockify_settings_id === null || (is_array($clockify_settings_id) && count($clockify_settings_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clockify_settings_id when calling deleteClockifySettings'
            );
        }
        if (strlen($clockify_settings_id) > 26) {
            throw new \InvalidArgumentException('invalid length for "$clockify_settings_id" when calling ClockifySettingsApi.deleteClockifySettings, must be smaller than or equal to 26.');
        }
        if (strlen($clockify_settings_id) < 26) {
            throw new \InvalidArgumentException('invalid length for "$clockify_settings_id" when calling ClockifySettingsApi.deleteClockifySettings, must be bigger than or equal to 26.');
        }
        if (!preg_match("/^[0-9A-HJ-KM-NP-TV-Z]{26}$/", $clockify_settings_id)) {
            throw new \InvalidArgumentException("invalid value for \"clockify_settings_id\" when calling ClockifySettingsApi.deleteClockifySettings, must conform to the pattern /^[0-9A-HJ-KM-NP-TV-Z]{26}$/.");
        }
        

        $resourcePath = '/api/admin/clockify_settings/{clockifySettingsId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($clockify_settings_id !== null) {
            $resourcePath = str_replace(
                '{' . 'clockifySettingsId' . '}',
                ObjectSerializer::toPathValue($clockify_settings_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getClockifySettings
     *
     * Retrieve MOCO Settings
     *
     * @param  string $clockify_settings_id clockify_settings_id (required)
     * @param  string $include The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettings'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Skriptfabrik\ApiClient\Model\ClockifySettingsResponse|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError
     */
    public function getClockifySettings($clockify_settings_id, $include = null, string $contentType = self::contentTypes['getClockifySettings'][0])
    {
        list($response) = $this->getClockifySettingsWithHttpInfo($clockify_settings_id, $include, $contentType);
        return $response;
    }

    /**
     * Operation getClockifySettingsWithHttpInfo
     *
     * Retrieve MOCO Settings
     *
     * @param  string $clockify_settings_id (required)
     * @param  string $include The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettings'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Skriptfabrik\ApiClient\Model\ClockifySettingsResponse|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getClockifySettingsWithHttpInfo($clockify_settings_id, $include = null, string $contentType = self::contentTypes['getClockifySettings'][0])
    {
        $request = $this->getClockifySettingsRequest($clockify_settings_id, $include, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Skriptfabrik\ApiClient\Model\JsonApiError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\JsonApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\JsonApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Skriptfabrik\ApiClient\Model\JsonApiError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\JsonApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\JsonApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Skriptfabrik\ApiClient\Model\JsonApiError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\JsonApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\JsonApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getClockifySettingsAsync
     *
     * Retrieve MOCO Settings
     *
     * @param  string $clockify_settings_id (required)
     * @param  string $include The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getClockifySettingsAsync($clockify_settings_id, $include = null, string $contentType = self::contentTypes['getClockifySettings'][0])
    {
        return $this->getClockifySettingsAsyncWithHttpInfo($clockify_settings_id, $include, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getClockifySettingsAsyncWithHttpInfo
     *
     * Retrieve MOCO Settings
     *
     * @param  string $clockify_settings_id (required)
     * @param  string $include The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getClockifySettingsAsyncWithHttpInfo($clockify_settings_id, $include = null, string $contentType = self::contentTypes['getClockifySettings'][0])
    {
        $returnType = '\Skriptfabrik\ApiClient\Model\ClockifySettingsResponse';
        $request = $this->getClockifySettingsRequest($clockify_settings_id, $include, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getClockifySettings'
     *
     * @param  string $clockify_settings_id (required)
     * @param  string $include The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getClockifySettingsRequest($clockify_settings_id, $include = null, string $contentType = self::contentTypes['getClockifySettings'][0])
    {

        // verify the required parameter 'clockify_settings_id' is set
        if ($clockify_settings_id === null || (is_array($clockify_settings_id) && count($clockify_settings_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clockify_settings_id when calling getClockifySettings'
            );
        }
        if (strlen($clockify_settings_id) > 26) {
            throw new \InvalidArgumentException('invalid length for "$clockify_settings_id" when calling ClockifySettingsApi.getClockifySettings, must be smaller than or equal to 26.');
        }
        if (strlen($clockify_settings_id) < 26) {
            throw new \InvalidArgumentException('invalid length for "$clockify_settings_id" when calling ClockifySettingsApi.getClockifySettings, must be bigger than or equal to 26.');
        }
        if (!preg_match("/^[0-9A-HJ-KM-NP-TV-Z]{26}$/", $clockify_settings_id)) {
            throw new \InvalidArgumentException("invalid value for \"clockify_settings_id\" when calling ClockifySettingsApi.getClockifySettings, must conform to the pattern /^[0-9A-HJ-KM-NP-TV-Z]{26}$/.");
        }
        


        $resourcePath = '/api/admin/clockify_settings/{clockifySettingsId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include,
            'include', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($clockify_settings_id !== null) {
            $resourcePath = str_replace(
                '{' . 'clockifySettingsId' . '}',
                ObjectSerializer::toPathValue($clockify_settings_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getClockifySettingsCollection
     *
     * Retrieve Clockify Settings Collection
     *
     * @param  float $limit The Limit Query Parameter. (optional, default to 10)
     * @param  float $page The Page Query Parameter. (optional, default to 1)
     * @param  string $included The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettingsCollection'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Skriptfabrik\ApiClient\Model\ClockifySettingsCollectionResponse|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError
     */
    public function getClockifySettingsCollection($limit = 10, $page = 1, $included = null, string $contentType = self::contentTypes['getClockifySettingsCollection'][0])
    {
        list($response) = $this->getClockifySettingsCollectionWithHttpInfo($limit, $page, $included, $contentType);
        return $response;
    }

    /**
     * Operation getClockifySettingsCollectionWithHttpInfo
     *
     * Retrieve Clockify Settings Collection
     *
     * @param  float $limit The Limit Query Parameter. (optional, default to 10)
     * @param  float $page The Page Query Parameter. (optional, default to 1)
     * @param  string $included The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettingsCollection'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Skriptfabrik\ApiClient\Model\ClockifySettingsCollectionResponse|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError|\Skriptfabrik\ApiClient\Model\JsonApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getClockifySettingsCollectionWithHttpInfo($limit = 10, $page = 1, $included = null, string $contentType = self::contentTypes['getClockifySettingsCollection'][0])
    {
        $request = $this->getClockifySettingsCollectionRequest($limit, $page, $included, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Skriptfabrik\ApiClient\Model\ClockifySettingsCollectionResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\ClockifySettingsCollectionResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\ClockifySettingsCollectionResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\Skriptfabrik\ApiClient\Model\JsonApiError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\JsonApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\JsonApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\Skriptfabrik\ApiClient\Model\JsonApiError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\JsonApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\JsonApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Skriptfabrik\ApiClient\Model\JsonApiError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Skriptfabrik\ApiClient\Model\JsonApiError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Skriptfabrik\ApiClient\Model\JsonApiError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Skriptfabrik\ApiClient\Model\ClockifySettingsCollectionResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\ClockifySettingsCollectionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getClockifySettingsCollectionAsync
     *
     * Retrieve Clockify Settings Collection
     *
     * @param  float $limit The Limit Query Parameter. (optional, default to 10)
     * @param  float $page The Page Query Parameter. (optional, default to 1)
     * @param  string $included The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettingsCollection'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getClockifySettingsCollectionAsync($limit = 10, $page = 1, $included = null, string $contentType = self::contentTypes['getClockifySettingsCollection'][0])
    {
        return $this->getClockifySettingsCollectionAsyncWithHttpInfo($limit, $page, $included, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getClockifySettingsCollectionAsyncWithHttpInfo
     *
     * Retrieve Clockify Settings Collection
     *
     * @param  float $limit The Limit Query Parameter. (optional, default to 10)
     * @param  float $page The Page Query Parameter. (optional, default to 1)
     * @param  string $included The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettingsCollection'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getClockifySettingsCollectionAsyncWithHttpInfo($limit = 10, $page = 1, $included = null, string $contentType = self::contentTypes['getClockifySettingsCollection'][0])
    {
        $returnType = '\Skriptfabrik\ApiClient\Model\ClockifySettingsCollectionResponse';
        $request = $this->getClockifySettingsCollectionRequest($limit, $page, $included, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getClockifySettingsCollection'
     *
     * @param  float $limit The Limit Query Parameter. (optional, default to 10)
     * @param  float $page The Page Query Parameter. (optional, default to 1)
     * @param  string $included The Include Query Parameter. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getClockifySettingsCollection'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getClockifySettingsCollectionRequest($limit = 10, $page = 1, $included = null, string $contentType = self::contentTypes['getClockifySettingsCollection'][0])
    {

        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ClockifySettingsApi.getClockifySettingsCollection, must be bigger than or equal to 1.');
        }
        
        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling ClockifySettingsApi.getClockifySettingsCollection, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/api/admin/clockify_settings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $included,
            'included', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateClockifySettings
     *
     * Update Clockify Settings
     *
     * @param  string $clockify_settings_id clockify_settings_id (required)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsUpdateRequest $clockify_settings_update_request Update Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateClockifySettings'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateClockifySettings($clockify_settings_id, $clockify_settings_update_request = null, string $contentType = self::contentTypes['updateClockifySettings'][0])
    {
        $this->updateClockifySettingsWithHttpInfo($clockify_settings_id, $clockify_settings_update_request, $contentType);
    }

    /**
     * Operation updateClockifySettingsWithHttpInfo
     *
     * Update Clockify Settings
     *
     * @param  string $clockify_settings_id (required)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsUpdateRequest $clockify_settings_update_request Update Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateClockifySettings'] to see the possible values for this operation
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateClockifySettingsWithHttpInfo($clockify_settings_id, $clockify_settings_update_request = null, string $contentType = self::contentTypes['updateClockifySettings'][0])
    {
        $request = $this->updateClockifySettingsRequest($clockify_settings_id, $clockify_settings_update_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Skriptfabrik\ApiClient\Model\JsonApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateClockifySettingsAsync
     *
     * Update Clockify Settings
     *
     * @param  string $clockify_settings_id (required)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsUpdateRequest $clockify_settings_update_request Update Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateClockifySettingsAsync($clockify_settings_id, $clockify_settings_update_request = null, string $contentType = self::contentTypes['updateClockifySettings'][0])
    {
        return $this->updateClockifySettingsAsyncWithHttpInfo($clockify_settings_id, $clockify_settings_update_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateClockifySettingsAsyncWithHttpInfo
     *
     * Update Clockify Settings
     *
     * @param  string $clockify_settings_id (required)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsUpdateRequest $clockify_settings_update_request Update Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateClockifySettingsAsyncWithHttpInfo($clockify_settings_id, $clockify_settings_update_request = null, string $contentType = self::contentTypes['updateClockifySettings'][0])
    {
        $returnType = '';
        $request = $this->updateClockifySettingsRequest($clockify_settings_id, $clockify_settings_update_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateClockifySettings'
     *
     * @param  string $clockify_settings_id (required)
     * @param  \Skriptfabrik\ApiClient\Model\ClockifySettingsUpdateRequest $clockify_settings_update_request Update Clockify Settings Request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateClockifySettings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateClockifySettingsRequest($clockify_settings_id, $clockify_settings_update_request = null, string $contentType = self::contentTypes['updateClockifySettings'][0])
    {

        // verify the required parameter 'clockify_settings_id' is set
        if ($clockify_settings_id === null || (is_array($clockify_settings_id) && count($clockify_settings_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clockify_settings_id when calling updateClockifySettings'
            );
        }
        if (strlen($clockify_settings_id) > 26) {
            throw new \InvalidArgumentException('invalid length for "$clockify_settings_id" when calling ClockifySettingsApi.updateClockifySettings, must be smaller than or equal to 26.');
        }
        if (strlen($clockify_settings_id) < 26) {
            throw new \InvalidArgumentException('invalid length for "$clockify_settings_id" when calling ClockifySettingsApi.updateClockifySettings, must be bigger than or equal to 26.');
        }
        if (!preg_match("/^[0-9A-HJ-KM-NP-TV-Z]{26}$/", $clockify_settings_id)) {
            throw new \InvalidArgumentException("invalid value for \"clockify_settings_id\" when calling ClockifySettingsApi.updateClockifySettings, must conform to the pattern /^[0-9A-HJ-KM-NP-TV-Z]{26}$/.");
        }
        


        $resourcePath = '/api/admin/clockify_settings/{clockifySettingsId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($clockify_settings_id !== null) {
            $resourcePath = str_replace(
                '{' . 'clockifySettingsId' . '}',
                ObjectSerializer::toPathValue($clockify_settings_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/vnd.api+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($clockify_settings_update_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($clockify_settings_update_request));
            } else {
                $httpBody = $clockify_settings_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
