<?php
/**
 * WebhooksApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Skriptfabrik\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * skriptfabrik API
 *
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Skriptfabrik\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Skriptfabrik\ApiClient\ApiException;
use Skriptfabrik\ApiClient\Configuration;
use Skriptfabrik\ApiClient\HeaderSelector;
use Skriptfabrik\ApiClient\ObjectSerializer;

/**
 * WebhooksApi Class Doc Comment
 *
 * @category Class
 * @package  Skriptfabrik\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhooksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation executeClockifyWebhook
     *
     * Execute Clockify Webhook
     *
     * @param  string $clockify_hook_id clockify_hook_id (required)
     * @param  string $clockify_signature Signing secret from webhook configuration (required)
     * @param  string $clockify_webhook_event_type Webhook event name (required)
     * @param  \Skriptfabrik\ApiClient\Model\ExecuteClockifyWebhookRequest $execute_clockify_webhook_request Execute Clockify Webhook Request (optional)
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function executeClockifyWebhook($clockify_hook_id, $clockify_signature, $clockify_webhook_event_type, $execute_clockify_webhook_request = null)
    {
        $this->executeClockifyWebhookWithHttpInfo($clockify_hook_id, $clockify_signature, $clockify_webhook_event_type, $execute_clockify_webhook_request);
    }

    /**
     * Operation executeClockifyWebhookWithHttpInfo
     *
     * Execute Clockify Webhook
     *
     * @param  string $clockify_hook_id (required)
     * @param  string $clockify_signature Signing secret from webhook configuration (required)
     * @param  string $clockify_webhook_event_type Webhook event name (required)
     * @param  \Skriptfabrik\ApiClient\Model\ExecuteClockifyWebhookRequest $execute_clockify_webhook_request Execute Clockify Webhook Request (optional)
     *
     * @throws \Skriptfabrik\ApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function executeClockifyWebhookWithHttpInfo($clockify_hook_id, $clockify_signature, $clockify_webhook_event_type, $execute_clockify_webhook_request = null)
    {
        $request = $this->executeClockifyWebhookRequest($clockify_hook_id, $clockify_signature, $clockify_webhook_event_type, $execute_clockify_webhook_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            
            }
            throw $e;
        }
    }

    /**
     * Operation executeClockifyWebhookAsync
     *
     * Execute Clockify Webhook
     *
     * @param  string $clockify_hook_id (required)
     * @param  string $clockify_signature Signing secret from webhook configuration (required)
     * @param  string $clockify_webhook_event_type Webhook event name (required)
     * @param  \Skriptfabrik\ApiClient\Model\ExecuteClockifyWebhookRequest $execute_clockify_webhook_request Execute Clockify Webhook Request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function executeClockifyWebhookAsync($clockify_hook_id, $clockify_signature, $clockify_webhook_event_type, $execute_clockify_webhook_request = null)
    {
        return $this->executeClockifyWebhookAsyncWithHttpInfo($clockify_hook_id, $clockify_signature, $clockify_webhook_event_type, $execute_clockify_webhook_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation executeClockifyWebhookAsyncWithHttpInfo
     *
     * Execute Clockify Webhook
     *
     * @param  string $clockify_hook_id (required)
     * @param  string $clockify_signature Signing secret from webhook configuration (required)
     * @param  string $clockify_webhook_event_type Webhook event name (required)
     * @param  \Skriptfabrik\ApiClient\Model\ExecuteClockifyWebhookRequest $execute_clockify_webhook_request Execute Clockify Webhook Request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function executeClockifyWebhookAsyncWithHttpInfo($clockify_hook_id, $clockify_signature, $clockify_webhook_event_type, $execute_clockify_webhook_request = null)
    {
        $returnType = '';
        $request = $this->executeClockifyWebhookRequest($clockify_hook_id, $clockify_signature, $clockify_webhook_event_type, $execute_clockify_webhook_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'executeClockifyWebhook'
     *
     * @param  string $clockify_hook_id (required)
     * @param  string $clockify_signature Signing secret from webhook configuration (required)
     * @param  string $clockify_webhook_event_type Webhook event name (required)
     * @param  \Skriptfabrik\ApiClient\Model\ExecuteClockifyWebhookRequest $execute_clockify_webhook_request Execute Clockify Webhook Request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function executeClockifyWebhookRequest($clockify_hook_id, $clockify_signature, $clockify_webhook_event_type, $execute_clockify_webhook_request = null)
    {

        // verify the required parameter 'clockify_hook_id' is set
        if ($clockify_hook_id === null || (is_array($clockify_hook_id) && count($clockify_hook_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clockify_hook_id when calling executeClockifyWebhook'
            );
        }
        if (strlen($clockify_hook_id) > 26) {
            throw new \InvalidArgumentException('invalid length for "$clockify_hook_id" when calling WebhooksApi.executeClockifyWebhook, must be smaller than or equal to 26.');
        }
        if (strlen($clockify_hook_id) < 26) {
            throw new \InvalidArgumentException('invalid length for "$clockify_hook_id" when calling WebhooksApi.executeClockifyWebhook, must be bigger than or equal to 26.');
        }
        if (!preg_match("/^[0-9A-HJ-KM-NP-TV-Z]{26}$/", $clockify_hook_id)) {
            throw new \InvalidArgumentException("invalid value for \"clockify_hook_id\" when calling WebhooksApi.executeClockifyWebhook, must conform to the pattern /^[0-9A-HJ-KM-NP-TV-Z]{26}$/.");
        }


        // verify the required parameter 'clockify_signature' is set
        if ($clockify_signature === null || (is_array($clockify_signature) && count($clockify_signature) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clockify_signature when calling executeClockifyWebhook'
            );
        }

        // verify the required parameter 'clockify_webhook_event_type' is set
        if ($clockify_webhook_event_type === null || (is_array($clockify_webhook_event_type) && count($clockify_webhook_event_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clockify_webhook_event_type when calling executeClockifyWebhook'
            );
        }


        $resourcePath = '/api/webhooks/clockify/{clockifyHookId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($clockify_signature !== null) {
            $headerParams['clockify-signature'] = ObjectSerializer::toHeaderValue($clockify_signature);
        }
        // header params
        if ($clockify_webhook_event_type !== null) {
            $headerParams['clockify-webhook-event-type'] = ObjectSerializer::toHeaderValue($clockify_webhook_event_type);
        }

        // path params
        if ($clockify_hook_id !== null) {
            $resourcePath = str_replace(
                '{' . 'clockifyHookId' . '}',
                ObjectSerializer::toPathValue($clockify_hook_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($execute_clockify_webhook_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($execute_clockify_webhook_request));
            } else {
                $httpBody = $execute_clockify_webhook_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
